# Dockerfile for the SaaS API Lambda function
FROM public.ecr.aws/lambda/python:3.12

COPY pyproject.toml README.md ${LAMBDA_TASK_ROOT}/
COPY aavaaz/ ${LAMBDA_TASK_ROOT}/aavaaz/

RUN pip install --no-cache-dir "${LAMBDA_TASK_ROOT}[saas]"

CMD ["aavaaz.serverless.saas_lambda.handler"]
