apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rest
      port: {{ .Values.service.restPort }}
      targetPort: rest
      protocol: TCP
    - name: websocket
      port: {{ .Values.service.wsPort }}
      targetPort: websocket
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
