replicaCount: 1

image:
  repository: collabora/aavaaz
  tag: latest
  pullPolicy: IfNotPresent

model: large-v3
apiKey: ""
metricsPort: 0
batchInference: false

nodeSelector: {}
tolerations: []
env: []

service:
  type: ClusterIP
  restPort: 8000
  wsPort: 9090

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: aavaaz.local
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    memory: "8Gi"
    cpu: "2"
  limits:
    memory: "16Gi"
    nvidia.com/gpu: "1"
